version: '3.4'
services:
  mysql:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3331:3306"
    command: 'mysqld --default-authentication-plugin=mysql_native_password --binlog-format=row --binlog-row-image=full --max-connections=10000'
    extra_hosts:
       - "host.docker.internal:172.17.0.1"  

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.4
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - ./data/zookeeper/log/version-2:/var/lib/zookeeper/log/version-2
      - ./data/zookeeper/data/version-2:/var/lib/zookeeper/data/version-2
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  kafka:
    image: confluentinc/cp-kafka:6.2.4
    ports:
      - 9092:9092
      - 29092:29092
      - 29093:29093
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092,LL://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://host.docker.internal:9092,LL://127.0.0.1:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT,LL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka/secrets:/etc/kafka/secrets
      - ./data/kafka/data:/var/lib/kafka/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.2.4
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  
  debezium1:
    image: debezium/connect:2.2
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      CONFIG_STORAGE_TOPIC: _debezium-config
      OFFSET_STORAGE_TOPIC: _debezium-offsets
      STATUS_STORAGE_TOPIC: _debezium-status
    depends_on:
      - mysql
      - kafka
    extra_hosts:
      - "host.docker.internal:172.17.0.1"